#https://stackoverflow.com/questions/28097064/dockerignore-ignore-everything-except-a-file-and-the-dockerfile

# Ignore Everything
**

!pyscribble
!requirements.txt

#!pyproject.toml
#!uv.lock
#!README.md
!app.py

**/__pycache__
**/*.pyc
