# Workflow for running pre-commit checks and dependency analysis
# This workflow ensures code quality and dependency management

name: pre-commit

# Trigger the workflow on push events
on:
  push:

jobs:
  # Job to analyze dependencies using deptry
  deptry:
    runs-on: ubuntu-latest
    steps:
      # Set up the virtual environment for the repository
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.71

      # Run deptry to check for unused or missing dependencies
      - name: Run deptry
        shell: bash
        run: |
          python -m pip install --no-cache-dir deptry
          python -m deptry -vv .

  # Job to run pre-commit hooks on all files
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      # Run pre-commit hooks with verbose output on all files
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: '--verbose --all-files'
