name: pre-commit

on:
  push:

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'

      - name: Run deptry
        shell: bash
        run: |
          uv venv
          uv pip install --no-cache-dir -r requirements.txt
          uv pip install --no-cache-dir deptry

      - name: Run deptry
        shell: bash
        run: |
          uv run deptry -vv --per-rule-ignores "DEP002=kaleido" pyscribble
