# Workflow for running pre-commit checks and dependency analysis
# This workflow ensures code quality and dependency management

name: pre-commit

# Trigger the workflow on push events
on:
  push:

jobs:

  # Job to run pre-commit hooks on all files
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      # Run pre-commit hooks with verbose output on all files
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: '--verbose --all-files'
