name: pre-commit

on:
  push:

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - name: Run deptry
        shell: bash
        run: |
          python -m pip install --no-cache-dir deptry
          python -m deptry -vv --per-rule-ignores "DEP002=kaleido,DEP002=marimo" pyscribble

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: '--verbose --all-files'
