name: pre-commit

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: '--verbose --all-files'


  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Install deptry
        shell: bash
        run: |
          pip install --no-cache-dir deptry

      - name: Run deptry
        shell: bash
        run: |
          deptry -vv 'pyscribble'
