# Workflow for creating a new version release and deploying to GitHub Pages
# This workflow is manually triggered to:
# 1. Create a new version tag using semantic versioning
# 2. Convert the Marimo notebook to HTML-WASM format
# 3. Deploy the HTML to GitHub Pages

name: Bump version

# Trigger the workflow manually using the GitHub Actions UI
# This allows controlled releases when needed rather than on every push
on:
  workflow_dispatch

jobs:
  # Job to generate a new version tag based on semantic versioning
  # This creates a new git tag with an incremented version number
  tagging:
    permissions:
      contents: write  # Permission to write to repository contents (needed to create tags)
    runs-on: ubuntu-latest
    outputs:
      # This output variable makes the tag available to other jobs in the workflow
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      # Use the cradle/actions/tag action to generate a semantic version tag
      # This automatically determines the next version number based on commit messages
      - name: Generate Tag
        id: tag_version
        uses: tschm/cradle/actions/tag@v0.1.72
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Job to build the HTML-WASM version of the Marimo notebook
  # This job sets up the environment and converts the notebook to a deployable format
  marimo:
    runs-on: ubuntu-latest
    steps:
      # Set up the Python virtual environment with all required dependencies
      # This uses a reusable action from the cradle repository
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.72

      # Convert the Marimo notebook to HTML-WASM format
      # The WASM format allows for interactive elements to work in the browser
      - name: Convert notebook to HTML
        run: |
          #uv run pip install --no-cache-dir marimo
          mkdir -p artifacts/marimo
          uvx marimo export html-wasm app.py -o artifacts/marimo/index.html --mode run

      - name: Upload Marimo html files
        uses: actions/upload-artifact@v4
        with:
          name: marimo
          path: artifacts/marimo
          retention-days: 1

  book:
    runs-on: "ubuntu-latest"
    needs: [marimo]

    environment:
      name: github-pages

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: tschm/cradle/actions/book@v0.1.72
