name: Bump version

# Trigger the workflow manually using the GitHub Actions UI
on:
  workflow_dispatch

jobs:
  # Job to generate a new version tag
  tagging:
    permissions:
      contents: write  # Permission to write to repository contents (create tags)
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}  # This will output the tag for other jobs
    steps:
      # Generate a new version tag based on semantic versioning
      - name: Generate Tag
        id: tag_version
        uses: tschm/cradle/actions/tag@v0.1.69
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
