# Workflow for creating a new version release and building a Docker image
# This workflow is manually triggered to create a new version tag and build a Docker image

name: Bump version

# Trigger the workflow manually using the GitHub Actions UI
on:
  workflow_dispatch

jobs:
  # Job to generate a new version tag
  tag:
    permissions:
      contents: write  # Permission to write to repository contents (create tags)
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.tag }}  # This will output the tag for other jobs
    steps:
      # Generate a new version tag based on semantic versioning
      - name: Generate Tag
        id: tag_version
        uses: cvxgrp/.github/actions/tag@v2.2.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_package: 'false'

      # Output the generated tag for debugging purposes
      - name: Debug Output Tag
        run: |
            echo "Tag: ${{ steps.tag_version.outputs.tag }}"

  # Job to build and push a Docker image with the new version tag
  docker:
    needs: tag  # This job depends on the tag job
    permissions:
      contents: read  # Permission to read repository contents
      packages: write  # Permission to write to GitHub Packages

    runs-on: ubuntu-latest
    steps:
      # -----------------------------------------------------------------------------
      # Step 1: Checkout the repository
      # -----------------------------------------------------------------------------
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      # Build and push the Docker image with the new tag
      - name: Build and Push Docker Image
        uses: cvxgrp/.github/actions/docker@v2.2.7
        with:
          repository: ${{ github.repository }}
          tag: ${{ needs.tag.outputs.tag }}
          dockerfile-path: 'docker/Dockerfile'
          github_token: ${{ secrets.GITHUB_TOKEN }}
