# Workflow for running tests across multiple operating systems and Python versions
# This workflow ensures cross-platform compatibility and Python version support

name: TEST

# Trigger the workflow on push events
on:
  push:

jobs:
  # Main test job that runs the test suite
  test:

    # The type of runner that the job will run on (defined in matrix)
    runs-on: ${{ matrix.os }}

    # Matrix strategy to test multiple configurations
    strategy:
      matrix:
        # Test on Ubuntu, Windows, and macOS
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        # Test with Python 3.10, 3.11, 3.12, and 3.13
        python-version: [ '3.11', '3.12', '3.13' ]

    steps:
      # Check out the repository code
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      # Set up uv (Python package manager) with the specified Python version
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Extract dependencies from app.py
        shell: bash
        run: |
          grep -A 10 "# dependencies = \[" app.py | grep -E "^#\s+\".*\"" | cut -d'"' -f2 | xargs -I{} uv pip install {}

      # Create virtual environment and install dependencies
      - name: Run pytest
        shell: bash
        run: |
          uv venv
          uv pip install --no-cache-dir pytest pytest-cov


      # Execute the test suite using pytest with coverage
      - name: Run tests
        shell: bash
        run: |
          uv run python -m pytest -vv --cov=. --cov-report=term --cov-report=xml tests

      # Upload coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
